# Generated by Django 2.2.1 on 2019-05-27 11:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_id', models.BigIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('query_name', models.CharField(max_length=255)),
                ('parameters', models.CharField(max_length=255)),
                ('configured_emails', models.CharField(max_length=255)),
                ('schedule', models.CharField(max_length=255, null=True)),
                ('is_excel_required', models.BooleanField(default=False)),
                ('is_sftp_used', models.BooleanField(default=False)),
                ('sftp_username', models.CharField(max_length=255, null=True)),
                ('sftp_host', models.CharField(max_length=255, null=True)),
                ('sftp_password', models.CharField(max_length=255, null=True)),
                ('sftp_path', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(blank=True, db_column='added_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_by', to=settings.AUTH_USER_MODEL)),
                ('last_edited_by', models.ForeignKey(blank=True, db_column='last_edited_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
        migrations.CreateModel(
            name='Exports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_job_id', models.CharField(default='00000000-0000-0000-0000-000000000000', max_length=255)),
                ('query_status', models.CharField(default='INITIATED', max_length=255)),
                ('status', models.CharField(default='PENDING', max_length=255)),
                ('file_name', models.CharField(default='PENDING', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='redash.Jobs')),
            ],
            options={
                'db_table': 'exports',
            },
        ),
    ]
