# Generated by Django 2.2.1 on 2019-05-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='schedule',
            field=models.IntegerField(default=4),
        ),
    ]
