# Generated by Django 2.2.1 on 2019-05-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redash', '0003_exportlogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='exportlogs',
            name='error_message',
            field=models.TextField(default=''),
        ),
    ]
