# Generated by Django 2.2.1 on 2019-06-03 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redash', '0007_auto_20190603_2043'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobs',
            old_name='end_time',
            new_name='schedule_end_time',
        ),
        migrations.RenameField(
            model_name='jobs',
            old_name='start_time',
            new_name='schedule_start_time',
        ),
    ]
