# Generated by Django 2.2.1 on 2019-06-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redash', '0008_auto_20190603_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='should_be_zipped',
            field=models.BooleanField(default=False),
        ),
    ]
