# Generated by Django 2.2.1 on 2019-06-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redash', '0009_jobs_should_be_zipped'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='csv_delimiter',
            field=models.CharField(default=',', max_length=2),
        ),
    ]
