# Generated by Django 2.2.1 on 2019-06-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redash', '0010_jobs_csv_delimiter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='schedule_end_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='schedule_start_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
